/* ==========================================================
   outils/hreflang.js : met à jour les liens "hreflang" de toutes les pages.

   Les hreflang disent aux moteurs de recherche que chaque page existe en
   français ET en anglais. Ils doivent contenir l'adresse COMPLÈTE du site.
   Cette adresse est écrite UNE SEULE FOIS, dans js/config.js (urlSite).

   Utilisation (dans le dossier du projet) :
       node outils/hreflang.js

   Le jour où tu changes de domaine :
       1. modifie urlSite dans js/config.js
       2. lance  node outils/hreflang.js
   Le script réécrit le bloc entre les deux commentaires "hreflang:debut"
   et "hreflang:fin" de chaque page. Il est sans danger à relancer.
   ========================================================== */

const fs = require("fs");
const path = require("path");

const racine = path.join(__dirname, "..");
const PAGES = ["index.html", "verificateur.html", "guides.html", "securite.html", "a-propos.html", "confidentialite.html"];

// 1. Lire l'adresse du site dans js/config.js
const config = fs.readFileSync(path.join(racine, "js", "config.js"), "utf8");
const trouve = config.match(/urlSite:\s*"([^"]+)"/);
if (!trouve) {
  console.error("Erreur : urlSite est introuvable dans js/config.js");
  process.exit(1);
}
const base = trouve[1].endsWith("/") ? trouve[1] : trouve[1] + "/";
if (!/^https:\/\//.test(base)) {
  console.error("Erreur : urlSite doit commencer par https://  (trouvé : " + base + ")");
  process.exit(1);
}

// 2. Construire le bloc de liens pour une page (le même pour la version FR et EN)
function adresse(dossier, fichier) {
  // L'accueil est écrit sans "index.html" (https://site/ et https://site/en/)
  return base + dossier + (fichier === "index.html" ? "" : fichier);
}

function bloc(fichier, nl) {
  return [
    "  <!-- hreflang:debut (generated by outils/hreflang.js, do not edit by hand) -->",
    '  <link rel="alternate" hreflang="fr" href="' + adresse("", fichier) + '">',
    '  <link rel="alternate" hreflang="en" href="' + adresse("en/", fichier) + '">',
    '  <link rel="alternate" hreflang="x-default" href="' + adresse("", fichier) + '">',
    "  <!-- hreflang:fin -->"
  ].join(nl);
}

// 3. Mettre à jour les deux versions de chaque page qui existe dans les deux langues
let modifiees = 0;
PAGES.forEach(function (fichier) {
  const fr = path.join(racine, fichier);
  const en = path.join(racine, "en", fichier);
  if (!fs.existsSync(fr) || !fs.existsSync(en)) {
    console.log("(ignorée : " + fichier + " n'existe pas encore dans les deux langues)");
    return;
  }
  [fr, en].forEach(function (chemin) {
    const texte = fs.readFileSync(chemin, "utf8");
    const nl = texte.includes("\r\n") ? "\r\n" : "\n";
    const nouveau = bloc(fichier, nl);
    const marqueurs = /[ \t]*<!-- hreflang:debut[\s\S]*?<!-- hreflang:fin -->/;

    let resultat;
    if (marqueurs.test(texte)) {
      resultat = texte.replace(marqueurs, nouveau);              // le bloc existe : on le remplace
    } else {
      const ancre = '<link rel="stylesheet"';                     // sinon on l'ajoute avant la feuille de style
      const i = texte.indexOf(ancre);
      if (i === -1) { console.error("Erreur : pas de feuille de style dans " + chemin); process.exit(1); }
      const debutLigne = texte.lastIndexOf("\n", i) + 1;
      resultat = texte.slice(0, debutLigne) + nouveau + nl + nl + texte.slice(debutLigne);
    }
    if (resultat !== texte) {
      fs.writeFileSync(chemin, resultat);
      modifiees++;
      console.log("mise à jour : " + path.relative(racine, chemin));
    }
  });
});
console.log(modifiees + " fichier(s) modifié(s). Adresse utilisée : " + base);
